-- ============================================================================
-- Migration 005: Performance + Security Improvements
-- Generated by: ULTRA FULL SYSTEM AUDIT
-- Date: 2026-06-18
-- ============================================================================

-- ═════════════════════════════════════════════════════════════════════════════
-- 1. MISSING INDEXES (Performance)
-- ═════════════════════════════════════════════════════════════════════════════

-- conversations: frequently queried by client_id for context
CREATE INDEX IF NOT EXISTS idx_conversations_client_id 
    ON conversations(client_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at 
    ON conversations(created_at DESC);

-- bookings: queried by client_id, status, date
CREATE INDEX IF NOT EXISTS idx_bookings_client_id 
    ON bookings(client_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status 
    ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_date 
    ON bookings(date);
CREATE INDEX IF NOT EXISTS idx_bookings_market_id 
    ON bookings(market_id);

-- clients: queried by telegram_id, market_id
CREATE INDEX IF NOT EXISTS idx_clients_telegram_id 
    ON clients(telegram_id);
CREATE INDEX IF NOT EXISTS idx_clients_market_id 
    ON clients(market_id);
CREATE INDEX IF NOT EXISTS idx_clients_stage 
    ON clients(stage);

-- tours: queried by market_id, category, active
CREATE INDEX IF NOT EXISTS idx_tours_market_id 
    ON tours(market_id);
CREATE INDEX IF NOT EXISTS idx_tours_category 
    ON tours(category);
CREATE INDEX IF NOT EXISTS idx_tours_active_sort 
    ON tours(active, sort_order);

-- client_memory: queried by client_id
CREATE INDEX IF NOT EXISTS idx_client_memory_client_id 
    ON client_memory(client_id);

-- knowledge: queried by market_id for context
CREATE INDEX IF NOT EXISTS idx_knowledge_market_id 
    ON knowledge(market_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_tags 
    ON knowledge USING gin(tags);

-- action_history: queried by client_id and timestamp
CREATE INDEX IF NOT EXISTS idx_action_history_client_id 
    ON action_history(client_id);
CREATE INDEX IF NOT EXISTS idx_action_history_created_at 
    ON action_history(created_at DESC);

-- payments: queried by booking_id
CREATE INDEX IF NOT EXISTS idx_payments_booking_id 
    ON payments(booking_id);

-- reviews: queried by tour_id, client_id
CREATE INDEX IF NOT EXISTS idx_reviews_tour_id 
    ON reviews(tour_id);
CREATE INDEX IF NOT EXISTS idx_reviews_client_id 
    ON reviews(client_id);

-- ═════════════════════════════════════════════════════════════════════════════
-- 2. MISSING RLS POLICIES (Security)
-- ═════════════════════════════════════════════════════════════════════════════

-- Enable RLS on all tables (idempotent)
ALTER TABLE IF EXISTS bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reviews ENABLE ROW LEVEL SECURITY;

-- bookings: anon can only read their own via RPC, service_role full access
DROP POLICY IF EXISTS "bookings_service_full" ON bookings;
CREATE POLICY "bookings_service_full" 
    ON bookings FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

DROP POLICY IF EXISTS "bookings_anon_read" ON bookings;
CREATE POLICY "bookings_anon_read" 
    ON bookings FOR SELECT 
    TO anon 
    USING (true);  -- Controlled via RPC parameters

-- payments: restrict access to service_role only
DROP POLICY IF EXISTS "payments_service_full" ON payments;
CREATE POLICY "payments_service_full" 
    ON payments FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- reviews: anon can insert, service_role full access
DROP POLICY IF EXISTS "reviews_anon_insert" ON reviews;
CREATE POLICY "reviews_anon_insert" 
    ON reviews FOR INSERT 
    TO anon 
    WITH CHECK (true);

DROP POLICY IF EXISTS "reviews_service_full" ON reviews;
CREATE POLICY "reviews_service_full" 
    ON reviews FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- conversations: add rate limiting check (max 100 messages per client per hour)
-- Note: This is a soft limit enforced at the application level
CREATE OR REPLACE FUNCTION check_conversation_rate_limit(p_client_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    msg_count INT;
BEGIN
    SELECT COUNT(*) INTO msg_count
    FROM conversations
    WHERE client_id = p_client_id
      AND created_at > NOW() - INTERVAL '1 hour';
    
    RETURN msg_count < 100;  -- Max 100 messages per hour per client
END;
$$;

-- Update conversations RLS to include rate limit check
DROP POLICY IF EXISTS "conversations_anon_insert_site" ON conversations;
CREATE POLICY "conversations_anon_insert_site" 
    ON conversations FOR INSERT 
    TO anon 
    WITH CHECK (
        check_conversation_rate_limit(client_id)
    );

-- ═════════════════════════════════════════════════════════════════════════════
-- 3. COMPOSITE INDEXES (Query Performance)
-- ═════════════════════════════════════════════════════════════════════════════

-- Frequent query pattern: get active tours by market, ordered by sort
CREATE INDEX IF NOT EXISTS idx_tours_market_active_sort 
    ON tours(market_id, active, sort_order) 
    WHERE active = true;

-- Frequent query pattern: get bookings for reminders (status + date)
CREATE INDEX IF NOT EXISTS idx_bookings_status_date 
    ON bookings(status, date) 
    WHERE status IN ('pending', 'confirmed');

-- Frequent query pattern: clients by stage for funnel analysis
CREATE INDEX IF NOT EXISTS idx_clients_stage_market 
    ON clients(stage, market_id);

-- ═════════════════════════════════════════════════════════════════════════════
-- 4. TABLE MAINTENANCE FUNCTIONS
-- ═════════════════════════════════════════════════════════════════════════════

-- Analyze tables for query planner
ANALYZE conversations;
ANALYZE bookings;
ANALYZE clients;
ANALYZE tours;
ANALYZE client_memory;
ANALYZE payments;
ANALYZE reviews;
ANALYZE action_history;

-- ═════════════════════════════════════════════════════════════════════════════
-- 5. VERIFICATION QUERIES
-- ═════════════════════════════════════════════════════════════════════════════
-- Run these to verify indexes were created:
-- SELECT schemaname, tablename, indexname, indexdef 
-- FROM pg_indexes 
-- WHERE schemaname = 'public' 
-- ORDER BY tablename, indexname;

-- Run these to find unused indexes:
-- SELECT schemaname, tablename, indexname, idx_scan 
-- FROM pg_stat_user_indexes 
-- WHERE idx_scan = 0 
-- ORDER BY tablename;